### ISSUE TITLE
Types representation is not helpful

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#141]
Currently the representations for types and enums aren't really helpful, especially while debugging:

```
>>> import strawberry
>>> @strawberry.input
... class Example:
...     arg: str
...
>>> Example
<class '__main__.Example'>
>>> x = Example("abc")
>>> x
input Example {
  arg: String!
}
```

I think we should move the current representation to be used only when using the class and not an instance, for the instances we can keep what dataclasses is giving us:

    >>> @dataclasses.dataclass()
    ... class Example:
    ...     arg: str
    ...
    >>> Example("abc")
    Example(arg='abc')

**Comment by sciyoshi** [comment]
This isn't really possible to do using a class decorator, since customizing the `repr` for a type involves metaclasses and you can't change that after the type has been created. There's a few alternatives here:

1. Introduce a metaclass + base class instead of the `strawberry.type` decorator, which would let you do this. Changes how you use the library, diverges from how you expect dataclasses to work, probably not worth it.
2. Use dataclasses' default repr behavior, and add a repr to the actual GraphQL type, i.e. `repr(Example.field)`. Requires either monkeypatching or extending `graphql` types, or upstreaming this behavior to graphql-core-next.
3. Remove all custom `repr` behavior.

I'd personally lean towards #3, or maybe #2 if upstream would be interested in changing `__repr__` on types.

**Comment by patrick91** [comment]
We could have a custom print that works with our types, I don't think graphql-core will want to change behaviours :)

So I'd do 3 plus a utility function that knows how to print our types. I think in future we will probably customise the printer anyway (to support schema directives), so I think it is fine using a custom function :)

**Comment by patrick91** [comment]
I've found a way to do this, but is not that nice: https://stackoverflow.com/a/56123966, but for now I'll remove the custom repr :)
