### ISSUE TITLE
Move CI to GitHub actions and add tests on windows 

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#160]
There's a PR open for this, might be worth picking it up again: https://github.com/strawberry-graphql/strawberry/pull/148

So we can use GitHub Actions to run tests on windows as well as linux and Mac OS :)

TODO

- [x] Run release on github actions (currently it is on circle ci)
- [ ] Run tests on windows

**Comment by zhidelev** [comment]
Hello, @patrick91 , I would like to work on this issue.  I decided to run tests on Windows and mypy tests failed because of the pytest_mypy plugin using https://pypi.org/project/capturer which does not support Windows. So I will think about a workaround for this case. Other test cases passed on Windows.

**Comment by patrick91** [comment]
@zhidelev thanks! that's really appreciated!

**Comment by patrick91** [comment]
Migration from circle ci to GitHub actions is done here: https://github.com/strawberry-graphql/strawberry/pull/954

**Comment by marcoacierno** [comment]
The only thing left here is running tests on windows?
