### ISSUE TITLE
How to help funding this project

### ISSUE THREAD

**Issue by justuswilhelm** [strawberry-graphql/strawberry#1799]
Hi, I'm interested in seeing a django compatible graphql implementation see succeed longterm. How can my company help finance this project?

**Comment by bellini666** [comment]
Hey @justuswilhelm ,

As @patrick91 said, soon most of the improvements and other nice features from `strawberry-django-plus` are going to be merged into `strawberry-graphql-django`, and the later will also become a first class citizen integration and be merged into the official monorepo (this one). That is unfortunately taking a bit more time than I would like it to take because I've also been more busy than I was planning to recently.

But we share the same interest regarding the success of both strawberry and strawberry+django :). I'm using strawberry+django for all of my company's new projects (and also migrating some older ones using graphene+django to it), the reason why I created `strawberry-django-plus` and also accept Patrick's invite to become a strawberry dev, to help achieve that goal!

> Maybe @bellini666 could be interested too since he's been working the most on the django integration lately :)

Sure! Would love to participate in that call :)

**Comment by justuswilhelm** [comment]
Hello both of you, I would love to have a chat with you and talk about how we can work together. I've just ported my company's main product from graphene to strawberry and really enjoy how much simpler everything is. However given Graphene's unclear future I am interested in seeing strawberry really taking off and being maintained for the next 5+ years to come. I'm willing to put money where my mouth is so if you could set up some kind of financial infrastructure for funding this project that would be greatly appreciated.

Is there a way to reach you outside of GitHub?

**Comment by justuswilhelm** [comment]
Btw I've petitioned a graphql server benchmark to add your project: https://github.com/graphql-crystal/benchmarks/issues/12#issuecomment-1093251167

**Comment by patrick91** [comment]
> Hello both of you, I would love to have a chat with you and talk about how we can work together. I've just ported my company's main product from graphene to strawberry and really enjoy how much simpler everything is. However given Graphene's unclear future I am interested in seeing strawberry really taking off and being maintained for the next 5+ years to come. I'm willing to put money where my mouth is so if you could set up some kind of financial infrastructure for funding this project that would be greatly appreciated.
> 
> Is there a way to reach you outside of GitHub?

I think discord could be the best option -> https://strawberry.rocks/discord

We were thinking of properly setting up a open collective, but we never got around that, maybe you have some suggestions 😊

**Comment by justuswilhelm** [comment]
I will write you on Discord :+1

**Comment by DoctorJohn** [comment]
Looks like this discussion has been moved to Discord. I'm currently closing issues that appear to be resolved. Feel free to reopen if needed :)
