### ISSUE TITLE
0.107.0 GET queries doesn't work. 

### ISSUE THREAD

**Issue by leo6104** [strawberry-graphql/strawberry#1818]
I was waiting for GET queries support and it seems 0.107.0 support GET queries. 

Really thanks for your hard works. @MattExact  @patrick91 

In my production project, turn on 'useGetForQueries' and then i got an error. 

![image](https://user-images.githubusercontent.com/7777929/163792364-e32ce3b8-f4e6-4a9e-a1a6-0cd5935bde96.png)

It seems `raw_variable_values` doesn't parsed yet. 

Here is stack trace.
![image](https://user-images.githubusercontent.com/7777929/163792935-7cf0b12f-95f3-4204-84d4-04cc546c3912.png)

**Comment by MattExact** [comment]
Could you add a bit more information on your issue?
What extension are you using strawberry with?

**Comment by leo6104** [comment]
I use FastAPI. 

strawberry-graphql = { version = "0.106.3", extras = ["fastapi"] }

**Comment by MattExact** [comment]
Ok so looks like this is a problem with the parsing of `variable_values`

We're using the starlette `request.query_params._dict` which creates a `dict[str, str]`

So when we call `parse_request_data` which uses `data.get("variables")`, it returns a string instead of a dict.

We should probably have a step after getting the dictionary of query params that parses the `variables` from a `str` to a `dict[str, Any]`

We should probably check this works for the other integrations, I am pretty confident the parsing of `variable_values` will be broken in the ASGI extension as well.

**Comment by MattExact** [comment]
I'm working on a fix now 😊

**Comment by leo6104** [comment]
all bug fixed! Thank you for your contribution! 🚀
