### ISSUE TITLE
Is it possible to support subscription for flask

### ISSUE THREAD

**Issue by zhouyuf6741** [strawberry-graphql/strawberry#1956]
Hi there,

I am building an app with Flaks framework and migrating to fastAPI seems not feasible at the moment. Would it be possible to add subscription feature to flask here? 

I digged a little into this myself but failed to enable asgi/websockets at the same time.

Would love to learn more about if it is possible to do this for flask.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/1956">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1956/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/1956/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
Hey @zhouyuf6741, are you still interested in this?

From the top of my head, two solutions come into my mind.

1. One obviously would be to implement the graphql subscription protocols for Flask. That could be tricky though, since Flask apparently has no official websocket support (correct me if I'm wrong).

2. Maybe you could [run Flask as an ASGI app](https://flask.palletsprojects.com/en/2.1.x/deploying/asgi/) and the [strawberry-graphql ASGI app](https://strawberry.rocks/docs/integrations/asgi) in parallel and [delegate requests based on the used protocol](https://stackoverflow.com/questions/60182619/run-multiple-asgi-apps-in-same-thread-with-uvicorn) (http vs websocket) to either of the ASGI apps.

**Comment by zhouyuf6741** [comment]
Hi @DoctorJohn, thank you for the suggestions! We ended up deployed another service to delegate subscription requests.
