### ISSUE TITLE
strawberry-fastapi integration:  context['response'].background = BackgroundTask(calback) not invoked

### ISSUE THREAD

**Issue by BakinSergey** [strawberry-graphql/strawberry#2103]
```
#### gq types ####

@strawberry.type(description="mutations")
class Mutation:
    task_create = strawberry.mutation(
        resolver=task.create, description="New Task"
    )

#### deco  4 resolver  fns ####

async def user_action_audit(response):
     ...some stuff ...

def with_audit(gql_resolver: Callable[[Any], Awaitable[Any]]):
    @wraps(gql_resolver)
    async def wrapper(*args, **kwargs):
        response = await gql_resolver(*args, **kwargs)

        # https://strawberry.rocks/docs/integrations/asgi#setting-response-headers
        kwargs["info"].context["response"].set_cookie(key="kuka", value='puka')    - this WORK

        # https://strawberry.rocks/docs/integrations/asgi#setting-background-tasks  - NOT WORK(bg task NOT invoked)
        kwargs["info"].context["response"].background = BackgroundTask(user_action_audit, response)  

        # was discovered myself   - WORK(bg task invoked)
        kwargs['info'].context['background_tasks'].tasks.append(BackgroundTask(user_action_audit, response))  

        return response
    return wrapper

#### resolver fn ####

@with_audit
async def create(
    info: Info,
    user_id: Annotated[
        UUID, strawberry.argument(description="user id")
    ],
) -> Task:
    data = crud.task.create_for_user(info.context["db"], user_id=user_id)
    return cast(Task, data)
```

the problem is that no background task is called in the described [here](https://strawberry.rocks/docs/integrations/asgi#setting-background-tasks) way(see comments in code)

Ubuntu 20.04
python = "~3.8"
strawberry-graphql = {extras = ["fastapi"], version = "^0.108.0"}
fastapi = "^0.75.2"

**Comment by tsmith023** [comment]
I think this is a case of out-of-date documentation as your workaround appears to be the intended functionality.

Looking at [this](https://github.com/strawberry-graphql/strawberry/blob/e08b8884fb8a2c5420b36e96e0176c02c17fa899/strawberry/fastapi/router.py) and [this](https://github.com/encode/starlette/blob/master/starlette/background.py), it seems impossible to achieve the functionality as described in the documentation since `info.context["response"]` has no attribute `background`. Instead, `info.context` has `background_tasks` as a field (if a dictionary) or an attribute (if inheriting from `BaseContext`).

I will amend the documentation to better describe this situation and so hopefully resolve this issue :D

**Comment by BakinSergey** [comment]
it seems like it has, but not work(not handle), but in other case(for ex FileResponse) it works
![image](https://user-images.githubusercontent.com/24735040/185694872-017bd748-bf9b-45c0-84de-95688d8a9430.png)
![image](https://user-images.githubusercontent.com/24735040/185695112-f7f97aff-0238-4630-95de-7b68918c7882.png)

**Comment by BakinSergey** [comment]
i check - this(2) will work, but (1) in case of context['response'].background - will not
![image](https://user-images.githubusercontent.com/24735040/185695575-60dc0e9c-0dcf-4999-9cf5-5be4b7779d87.png)
![image](https://user-images.githubusercontent.com/24735040/185695858-60d1dde1-8f78-470a-be87-488fbf96b26a.png)

**Comment by tsmith023** [comment]
Ahh okay, interesting. I see what you're driving at! You may be mixing up the different Strawberry integrations.

You initially linked [here](https://strawberry.rocks/docs/integrations/asgi#setting-background-tasks), which actually applies to the Strawberry-_ASGI_ integration and not the Strawberry-_FastAPI_ integration. If you go [here](https://strawberry.rocks/docs/integrations/fastapi#setting-background-tasks) then you will see the correct FastAPI functionality that allows for adding background tasks to the context object, which is the functionality you desire.

Since these are different integrations, it's important that you use the correct functionality for the integration that you choose. You chose FastAPI, so you should follow [these docs](https://strawberry.rocks/docs/integrations/fastapi#setting-background-tasks).

**Comment by BakinSergey** [comment]
u right! 
i was only google by "Setting background tasks"  )))
Thx for your time!

**Comment by tsmith023** [comment]
Great! :D If you feel that this is resolved could you please close the issue, thanks!
