### ISSUE TITLE
Extension method request_on_start handles errors differently

### ISSUE THREAD

**Issue by ronaldnwilliams** [strawberry-graphql/strawberry#2249]
## Describe the Bug

Found a difference between the resolve and on_request_start method of custom extensions. If I raise an error in the resolve method, the client get back a 200 and a nice error message. If I raise an error in on_request_start the server crashes. For example, if I raise a ValueError() in each of them I get the following.

resolve response:
200 status code
```
{
  "data": null,
  "errors": [
    {
      "message": "An unknown error occurred.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "books"
      ]
    }
  ]
}
```

on_request_start response example:
500 status code 
```
{
  "errors": [
    {
      "message": "Unexpected token 'V', \"ValueError\"... is not valid JSON",
      "stack": "SyntaxError: Unexpected token 'V', \"ValueError\"... is not valid JSON"
    }
  ]
}
```

## System Information

 - Operating system: Mac Os - Monterey
 - Strawberry version (if applicable): 0.133.5

## Additional Context

```
class MyExtension(Extension):
    def resolve(self, _next, root, info, *args, **kwargs):
        raise ValueError()

    def on_request_start(self):
        raise ValueError()
```

**Comment by cake-monotone** [comment]
I found the same issue on `on_executing_start` and `on_executing_end` etc.

I think `strawberry` executes the methods in `Extension` (except `resolve`) without exception handling.

**Comment by jkimbo** [comment]
Thanks for the report @ronaldnwilliams . The resolve method is handled differently because it gets executed inside each field resolver and so any error gets handled like an error thrown inside a resolver (note the location and path metadata on the error when it's thrown in the resolve function). 

The other extension methods are called outside of the query resolution and they currently don't have any exception handling. IMO these errors should prologate up to the view layer and return a 500 http status code to the client. Not sure why it's triggering a JSON serialisation error though. What web framework are you using?

**Comment by patrick91** [comment]
> The other extension methods are called outside of the query resolution and they currently don't have any exception handling. IMO these errors should prologate up to the view layer and return a 500 http status code to the client. Not sure why it's triggering a JSON serialisation error though. What web framework are you using?

do you think this should be the case **also** for on on_executing_start/on_executing_end?

I was chatting with @ronaldnwilliams and they wanted to make an extension for permissions, but it would check for permissions at the start of the request/execution, and raise if the permissions are invalid. 

I think at least in on_executing_start/end we should treat errors the same way we treat them in the resolve hook, I'd find it inconsistent otherwise 😊

**Comment by jkimbo** [comment]
> I think at least in on_executing_start/end we should treat errors the same way we treat them in the resolve hook, I'd find it inconsistent otherwise 😊

We could catch exceptions and convert them to `GraphQLError`s without a location or path so that it's consistent with how errors are handled in resolvers. I think thats judgment call, I can see arguments for both ways. We should do it with all the extension hooks though, I don't see why `on_executing_{start,end}` should be special.

**Comment by patrick91** [comment]
> We should do it with all the extension hooks though, I don't see why `on_executing_{start,end}` should be special.

You're! I was thinking that on_request_start/end might be the one that is handled differently, since it is wraps the whole execution[1]

[1] and maybe it is a good place for us to allow setting custom status_codes?

**Comment by jkimbo** [comment]
`on_request_{start,end}` is the hook that wraps the whole execution (including parsing and validating the query). If we want to set status codes anywhere I think thats where we should do it. The naming also makes more sense if it becomes tied to the http request layer.

**Comment by patrick91** [comment]
> `on_request_{start,end}` is the hook that wraps the whole execution (including parsing and validating the query). If we want to set status codes anywhere I think thats where we should do it. The naming also makes more sense if it becomes tied to the http request layer.

Yup, I think we should open a discussion around that, also to define what on_request_start/end means in other context (websockets, sse and whatever comes next) 😊

**Comment by jerber** [comment]
For FastAPI this can be handled with a middleware. Here is mine that is working:

```
import typing as T
import time
from fastapi import Request, Response, FastAPI
from fastapi.responses import ORJSONResponse
from app.errors import DisplayException


def add_error_handling_and_process_time(app: FastAPI) -> None:
    @app.middleware("http")
    async def add_error_handling_and_process_time_header(
        request: Request, call_next: T.Any
    ) -> Response:
        start_time = time.time()
        try:
            response = await call_next(request)
        except DisplayException as e:
            response = ORJSONResponse({"errors": [e.message]})
            response.status_code = 400
        except Exception:
            response = ORJSONResponse({"errors": ["Internal Server Error"]})
            response.status_code = 500
        process_time = time.time() - start_time
        response.headers["X-Process-Time"] = str(process_time)
        return response
```

**Comment by ronaldnwilliams** [comment]
@patrick91 good to close or did you want to discuss this more / reuse?

**Comment by patrick91** [comment]
I'll close this, let's make a new issue if this comes up again 😊
