### ISSUE TITLE
FastAPI custom context doesn't work with `strawberry server`

### ISSUE THREAD

**Issue by judahrand** [strawberry-graphql/strawberry#2298]
## Describe the Bug

The context doesn't get passed to the requests when using `strawberry server`. When using the `starlette.testclient.TestClient` it does work.

Having read more about this it is almost certainly not supposed to work. However, the fact that this is undocumented makes it tricky to work out what is going on. 

## System Information

 - Operating system: MacOS 13.0
 - Strawberry version (if applicable): 0.138.1

## Additional Context

Minimal reproducible:

example.py
```
import strawberry
from strawberry.types import Info
from strawberry.fastapi import BaseContext, GraphQLRouter

from fastapi import Depends, FastAPI


@strawberry.type
class Query:
    @strawberry.field
    def abc(self, info: Info) -> str:
        assert info.context.request is not None
        assert info.context.strawberry == "rocks"
        return "abc"

class CustomContext(BaseContext):
    def __init__(self, rocks: str):
        self.strawberry = rocks

def custom_context_dependency() -> CustomContext:
    return CustomContext(rocks="rocks")

def get_context(custom_context: CustomContext = Depends(custom_context_dependency)):
    return custom_context

app = FastAPI()
schema = strawberry.Schema(query=Query)
graphql_app = GraphQLRouter(schema=schema, context_getter=get_context)
app.include_router(graphql_app, prefix="/graphql")
```

`strawberry server example`

then with `curl`:

```
❯ curl http://127.0.0.1:8000/graphql -H "Content-Type: application/json" -d '{"query": "{ abc }"}'
{"data":null,"errors":[{"message":"'dict' object has no attribute 'request'","locations":[{"line":1,"column":3}],"path":["abc"]}]}%
```

**Comment by tsmith023** [comment]
I think you're right that you need to infer from the docs that this won't work. Case-in-point, https://strawberry.rocks/docs/guides/server says `Sometimes you need to quickly prototype an API and don’t really need to use a framework like Flask or Django.` from which it must be inferred that this also applies to FastAPI.

This is where the `strawberry server` command is defined: https://github.com/strawberry-graphql/strawberry/blob/main/strawberry/cli/debug_server.py, and, as you can see on L15, the `app` instance is a Starlette app. Since context Dependency Injection is a novel aspect of FastAPI, it makes sense that it won't work.

@patrick91, assuming that this won't implemented, since `strawberry server` is meant for prototyping, a simple update of the docs to mention FastAPI should suffice?
