### ISSUE TITLE
Deprecated arguments no longer appear in introspection query but execute successfully

### ISSUE THREAD

**Issue by njdart** [strawberry-graphql/strawberry#2532]
## Describe the Bug

Including `deprecation_reason=".."` in a field argument's type definition removes the argument from the generated graphql schema, however use of the argument will execute successfully as expected.

```python
@strawberry.field
def get_foo(
    self,
    my_str: Annotated[
        Optional[str],
        strawberry.argument(
            deprecation_reason="If this is set, the graphiql playground will complain it doesn't exist!",
        ),
    ] = None,
) -> Optional[str]:
    return my_str
```

![image](https://user-images.githubusercontent.com/1180858/218082201-be7cf1db-e5f8-45f1-8e2c-07f4bc9ccd83.png)

## System Information

 - Operating system: Linux
 - Strawberry version (if applicable): tested in 0.155.2 and 0.156.3

**Comment by jkimbo** [comment]
Verified this bug and found the issue. Looks like a version of GraphiQL disabled argument deprecated introspection by default because it wasn't supported by all GraphQL server versions: https://github.com/graphql/graphiql/pull/2087

Created a fix here: https://github.com/strawberry-graphql/strawberry/pull/2575
