### ISSUE TITLE
relay: conflict with GlobalId of strawberry_django_plus

### ISSUE THREAD

**Issue by devkral** [strawberry-graphql/strawberry#2815]
I get the error:
strawberry.exceptions.scalar_already_registered.ScalarAlreadyRegisteredError: Scalar `GlobalID` has already been registered

I think it is because I use strawberry_django_plus and the new relay implementation.

I don't know on which side to report

**Comment by bellini666** [comment]
@devkral you are probably mixing both integrations (i.e. using `GlobalID` from strawberry while also using it from `strawberry-django-plus`)

I need to port strawberry-django-plus to use the core integration instead of its own, and I should do that this weekend. Then those kind of issues are not going to happen anymore :)

**Comment by devkral** [comment]
it was a gql.django.node which caused the problem

**Comment by bellini666** [comment]
@devkral I just released a new version of strawberry-django-plus, which removes its custom relay implementation and integrates on top of the official one: https://github.com/blb-ventures/strawberry-django-plus/releases/tag/v3.0.0
