### ISSUE TITLE
Pydantic V2 Support

### ISSUE THREAD

**Issue by thejaminator** [strawberry-graphql/strawberry#2978]
To try it out,
```
pip install strawberry-graphql==0.196.0.dev.1690222024
```

Please report any problems faced migrating in this mega issue

[Current yet to be merged MR here](https://github.com/strawberry-graphql/strawberry/pull/2972)

**Comment by rgon** [comment]
Support for [`from_pydantic` and `to_pydantic`](https://strawberry.rocks/docs/integrations/pydantic#converting-types) is not implemented yet.

It's defined in the original v1 implementation in: 
https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/object_type.py#L207-L212
https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/object_type.py#L279-L282

and also in 
[strawberry/experimental/pydantic/conversion.py#L62, `_convert_from_pydantic_to_strawberry_type`](https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/conversion.py#L62) and in `convert_strawberry_class_to_pydantic_model` for `to_pydantic`.

However, it's not present in [`theaminator's fork](https://github.com/thejaminator/strawberry/blob/587344c3d41fdf8875b2c8be2eec0267f16d6236/strawberry/experimental/pydantic/object_type.py#L223)

I suppose we could just add it back in. I suppose there aren't any tests for this functionality, since all seem to have passed.

**Comment by patrick91** [comment]
@rgon would you be interested in adding those tests? 😊 (also, thanks a lot for testing the pre-release!)

**Comment by thejaminator** [comment]
> to_pydantic

Thats interesting. 

> Support for [`from_pydantic` and `to_pydantic`](https://strawberry.rocks/docs/integrations/pydantic#converting-types) is not implemented yet.
> 
> It's defined in the original v1 implementation in:
> 
> https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/object_type.py#L207-L212
> 
> 
> https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/object_type.py#L279-L282
> 
> and there are also some references to it in [strawberry/experimental/pydantic/conversion.py#L62, `_convert_from_pydantic_to_strawberry_type`](https://github.com/strawberry-graphql/strawberry/blob/bb35e09e2ebd633ec43e71a50b4175975cb46c3b/strawberry/experimental/pydantic/conversion.py#L62) and in `convert_strawberry_class_to_pydantic_model` for `to_pydantic`.
> 
> However, none are present in [thejaminator's fork](https://github.com/thejaminator/strawberry/blob/587344c3d41fdf8875b2c8be2eec0267f16d6236/strawberry/experimental/pydantic/object_type.py#L223)
> 
> I suppose we could just add it back in. It also seems like there aren't any tests for this functionality, since all seem to have passed.

Thats interesting. Thanks for pointing that out! We do have tests for `tests/experimental/pydantic/test_conversion.py` though.
Are you getting the errors at runtime or due to mypy?

**Comment by rgon** [comment]
@patrick91 I will have to take a shot at this. Not an expert at that, but will take a shot at this in a few days if you don't mind a little post-PR guidance :)

@thejaminator no worries! Yes, I'm talking about defining custom `from_pydantic` and `to_pydantic` methods as described [here in the docs, in 'custom conversion logic'](https://strawberry.rocks/docs/integrations/pydantic#custom-conversion-logic) (whoops I linked to a different section initially, sorry for the confusion). I'm specifically talking about defining methods like this one (copied from the docs):
``` python

@strawberry.experimental.pydantic.type(model=User)
class UserType:
    id: strawberry.auto
    # Flatten the content dict into specific fields in the query
    content_name: Optional[str] = None
    content_description: Optional[str] = None

    @staticmethod
    def from_pydantic(instance: User, extra: Dict[str, Any] = None) -> "UserType":
        data = instance.dict()
        content = data.pop("content")
        data.update({f"content_{k.value}": v for k, v in content.items()})
        return UserType(**data)

    def to_pydantic(self) -> User:
        data = dataclasses.asdict(self)

        # Pull out the content_* fields into a dict
        content = {}
        for enum_member in ContentType:
            key = f"content_{enum_member.value}"
            if data.get(key) is not None:
                content[enum_member.value] = data.pop(key)
        return User(content=content, **data)
```

 I see no runtime/mypy errors. However, when implementing a custom 're'-serializer of sorts, with this pre-release these methods had no effect (not even print statements were called). Tracing the function back, I noticed that the check for custom-defined conversion methods is not yet implemented.

I think it can just be supported with a `has_custom_from_pydantic` check like in the v1 release.

**Comment by thejaminator** [comment]
@rgon thank you!
> Tracing the function back, I noticed that the check for custom-defined conversion methods is not yet implemented.
Thats weird. because I havent changed anything at all for that logic. it should be the same as V1. Not sure why that worked before but it doesn't now

**Comment by AlexTo** [comment]
is there a version that works with Pydantic v2 yet? :D very much appreciated  !!!

**Comment by patrick91** [comment]
@AlexTo we just released one! Feel free to open an issue if you find bugs! I'll close this issue 😊

**Comment by AlexTo** [comment]
@patrick91 that's awesome, will update right away, thank you
