### ISSUE TITLE
django hits DB twice when it accesses a cached_property field. (A django field with @cached_property decorator.)

### ISSUE THREAD

**Issue by shmoon-kr** [strawberry-graphql/strawberry#3329]
I was using strawberry graphql and noticed that my queries were very slow.

I thought it was strange, so I took a DB query log and found that strawberry and django have inefficient behavior when accessing cached_property.

Here is the model I created.

`class Member:`
`  birthday = models.DateTimeField()`
`  @cached_property`
`  age = datetime.timedelta ( datetime.datetime.now() - birthday ) / 365`

I defined the graphql type as it is in this django model and queried the entire member data.

`query {`
`  members {`
`    birthday`
`    age`
`  }`
`}`

This will initially execute the `SELECT birthday FROM members` query, and then later, once again, fire the same query n times against all IDs with the results.

`SELECT birthday FROM member WHERE id = 1;`
`ELECT birthday FROM member WHERE id = 2;`
`SELECT birthday FROM member WHERE id = 3;`
......

As a result, this GraphQL query will access the DB n+1 times when there is n data in the member table.
Since the birthday value is also present in the first query, it would be fine to calculate the age from it and cache it, but the cached_property doesn't behave that way and blows the second query. I haven't seen the exact code for this, but I'm guessing based on my comments that cached_property calculates and caches the value when it actually accesses the data, but it doesn't access the age value when the first query is executed, so it can't cache it.

This is not a problem when the amount of data is small, but as the amount of data increases, it causes a serious performance hit.
I was wondering if you could take a look at this?

 - Operating system: Ubuntu 22.04
 - Strawberry version (if applicable): the most recent version.

## Additional Context

Django 4.2.8

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3329">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3329/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3329/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@shmoon-kr could build a small reproduction for us? 😊

**Comment by shmoon-kr** [comment]
I encountered this issue while working on a project for my company, so I can't use the source code,
I've tried to reproduce the case by creating a simpler version, but it's not working.
I'm guessing that it's not the cached_property itself that's causing the problem, but rather the use of select_related with it. It's going to take me a bit more time to see what's happening more clearly and reproduce it, but I'll comment back as soon as I've simplified it and succeeded in reproducing it.

**Comment by patrick91** [comment]
@bellini666 might have some ideas then 😊

**Comment by bellini666** [comment]
Hey @shmoon-kr ,

First of all, are you using strawberry only or strawberrry_django? Based on your description, I'll assume it is strawberry_django and that you have the [query optimizer](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/optimizer/) enabled.

For that situation, the optimizer will call `.only()`/`.select_related()` on the queryset for the selected fields only. But it has to know that the fields were selected. When you retrieve something inside a `cached_property` such as the `age` in your example it would not know.

TBH your example would actually solve it because you are selecting `birthday` together with `age`, meaning that your query would guarantee that `birthday` is selected, but if you remove it and only select `age` then you would for sure see this problem happening.

For those cases you can give the resolver some [optimization hints](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/optimizer/#optimization-hints). Another possibility is to use a [model property](https://strawberry-graphql.github.io/strawberry-graphql-django/guide/optimizer/#optimization-hints-on-model-modelproperty) instead of your `cached_property`, which acts the same way when you pass `cached=True` to it, but does accept optimization hints as well.

Let me know if that explanation helps you. If not, a reproduction example might be required for me to understand what might be going on :)

**Comment by shmoon-kr** [comment]
Hi. @bellini666

Yes, exactly. I'm using strawberrry_django and I enabled query optimizer.

From your description I can roughly understand what is going on.
I will try to apply your suggestions one by one. If it doesn't work, I'll talk to you again.

Thanks!

**Comment by shmoon-kr** [comment]
The issue is completely resolved.

When I put the `birthday` and `age` fields in the query at the same time, django stopped making unnecessary accesses to the DB.

It's a workaround, but it's good enough for now, and since you also mentioned giving query hints, I think it's good enough.

Thanks.
