### ISSUE TITLE
enhancing robustness of int/float castings for string values containing commas

### ISSUE THREAD

**Issue by Speedy1991** [strawberry-graphql/strawberry#3412]
I run into this problem again and again and it is always annoying to fix it

## Feature Request Type

- [x] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

```
ValueError: could not convert string to float: '3,3'
  File "graphql/type/scalars.py", line 123, in serialize_float
    num = output_value if isinstance(output_value, float) else float(output_value
```

Currently values with `,` will break int/float resolvers, but most times this is not a real error.

It would be awesome if we can handle `,` like `.` if the value is a string like this:

```
output_value = output_value.replace(',', '.').strip() if isinstance(output_value, str) else output_value
num = output_value if isinstance(output_value, float) else float(output_value)
```

The same happens with integers

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3412">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3412/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3412/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
Hi thanks for the suggestion!

The exception you're referring to is coming from graphql-core which is a python library that stricly follows the graphql specification. That specificiation also requires floats to use a dot as a decorator. Straweberry too strictly follows the graphql specification, however, strawberry enables you to overwrite the float scalar if you want to.

Take a look at our scalars documentation to learn how to implement this for your schema in just a few lines: https://strawberry.rocks/docs/types/scalars

Feel free to add comments if you have questions about it. I'm closing this issue because adding this to strawberry itself would be out of scope for strawberry as described above.
