### ISSUE TITLE
`UnallowedReturnTypeForUnion` Error thrown when having a response of Union Type and using Generics since 0.229.0 release

### ISSUE THREAD

**Issue by jibujacobamboss** [strawberry-graphql/strawberry#3501]
## Describe the Bug
`UnallowedReturnTypeForUnion` Error thrown when having a response of Union Type and using Generics(with interface) since 0.229.0 release.
Sharing the playground [link](https://play.strawberry.rocks/?gist=a3c87c1b7816a2a3251cdf442b4569e1) showing the error for ease of replication.

This was a feature which was working but seems like it broke with the 0.229.0 release

## System Information

 - Operating system:
 - Strawberry version (if applicable): 0.229.0

## Additional Context

Playground Link : https://play.strawberry.rocks/?gist=a3c87c1b7816a2a3251cdf442b4569e1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3501">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3501/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3501/pledge.svg">
</picture>
</a>

**Comment by patrick91** [comment]
@jibujacobamboss sorry for the issue, hopefully the new release fixes it for you 😊

**Comment by jibujacobamboss** [comment]
> @jibujacobamboss sorry for the issue, hopefully the new release fixes it for you 😊

Thank you for the swift fix🚀

**Comment by sebastiandev** [comment]
@patrick91  Hi! I'm facing this issue again, I'm on version `0.283.3`
I'm using pagination defining a page with generics and returning `Page[MyType] | Error` and get the exact same error.   Was there a regression?

**Comment by patrick91** [comment]
@sebastiandev not sure, can you open a new issue with a minimal reproduction? 😊

**Comment by sebastiandev** [comment]
> [@sebastiandev](https://github.com/sebastiandev) not sure, can you open a new issue with a minimal reproduction? 😊

I think I know whats happening. It is not a regression, but my scenario is like this

In my queries/mutations I'm returning sqlalchemy objects.  The GQL types might expose the entire set of fields or a subset.  We usually have 1-1, but we might get a GQL type that resolves fields from multiple sqlalchemy models.

So when I build my Page object, I have
```python
return Page[Product](items=[SQLProduct(), SQLProductt()])
```

My guess is that somewhere in the resolution it is not resolving the type properly, so in the end i get the error "Page is not in the union types [Product, Error]"

The weird thing is that if I change my query to just return `Page[Product]` (instead of the union with Error), then that works just fine.

**Note:** I have a base class for all my gql types, where I configure the mapping to our sql types
where I  implement `is_type_of`. Here i check that the obj param matches with my mapping. This allows me to pass sqlobjects to resolvers that expect object types.  That's something we have been doing with graphene for ages, but found abit more challenging with strawberry because of all the type checking, but I feel like its how gql was meant to be. Otherwise I would have to convert all my results to gql types before returning them, which kinda defeats the purpose of having the field resolvers.

It looks something like this
```python
@strawberry.type
class BaseGQLType:
    """
    Base type for all GQL strawberry types.
    """

    __domain_type__: strawberry.Private[type | None] = None

    @classmethod
    def is_type_of(cls, obj: Any, _info: GraphQLResolveInfo) -> bool:
        logging.error(f"Checking is_type_of {cls} {obj}")
        if cls.__domain_type__ and isinstance(obj, (cls, cls.__domain_type__)):
            return True

        return super().is_type_of(obj, _info)
```

So my GQL Product type would look like

```python
@strawberry.type
class Product(BaseGQLType):
    __domain_type__ : strawberry.Private[type| None] = SQLProduct

    name: str
    price: Decimal
```
And my query would look like
```python

@strawberry.type
class Error(BaseGQLType):
    message: str


@strawberry.type
class Page(Generic[T], BaseGQLType):
    items: list[T]


def get_products() -> Page[Product] | Error:
    result = fetch_sql_products()
    return Page[Product](items=result)  # <== here's where we return a sql object instead of a gql object type


@strawberry.type
class Query:
    products: Page[Product] | Error = strawberry.field(resolver=get_products)
```

If I change to just return the generic Page (no union with error) it works
```python
def get_products() -> Page[Product]:
    result = fetch_sql_products()
    return Page[Product](items=result)


@strawberry.type
class Query:
    products: Page[Product] = strawberry.field(resolver=get_products)
```

I have also noticed that if I pass items as []  or a gql object type that I manually built to test this, then it passes
```python

# Any of this two work as well

def get_products() -> Page[Product] | Error:
    result = fetch_sql_products()
    return Page[Product](items=[])


def get_products() -> Page[Product] | Error:
    result = fetch_sql_products()
    return Page[Product](items=[Product(), Product()]  # fake the response with object types
```

So it looks like there's an issue with sending other than the actual gql type in the result when using unions of generics.
