### ISSUE TITLE
`on_ws_connect` return handling

### ISSUE THREAD

**Issue by tjcutajar** [strawberry-graphql/strawberry#3729]
Hi there,

I noticed this small difference between the return handling of the new `on_ws_connect` in `graphql_transport_ws` vs `graphql_ws`, notably a `None` value is not handled in `graphql_transport_ws`:

https://github.com/strawberry-graphql/strawberry/blob/633c9bc7c372ae69948efe87d8ee332b9e7a297a/strawberry/subscriptions/protocols/graphql_transport_ws/handlers.py#L193

Is there a specific reason for this, or could they be made the same?

Thanks.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3729">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3729/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3729/pledge.svg">
</picture>
</a>

**Comment by DoctorJohn** [comment]
Hi, as stated in our integrations' [docs](https://strawberry.rocks/docs/integrations/aiohttp#on_ws_connect), this is intentional.

> notably a None value is not handled in graphql_transport_ws

It is handled, however, differently than for the older subprotocol.

The reason for this is that in the newer subprotocol a payload can either be `undefined` (`strawberry.UNSET` in Python), the `null` JSON value (`None` in Python), or a JSON `object` (`dict` in Python). In the older subprotocol, however, a JSON value of `null` is not valid.

For compatibility reasons, if you return `None` from `on_ws_connect` it will be mapped to a `null` JSON value in the new subprotocol, while for the old subprotocol it will be handled as if the payload was undefined.

**Comment by tjcutajar** [comment]
@DoctorJohn Thanks for your feedback. 

With this explanation, should the None check then in fact be in the `graphql_transport_ws` handler? At the moment it returns 
`{"type": "connection_ack", "payload": null}` when returning None from `on_ws_connect` with `graphql_transport_ws`.

**Comment by DoctorJohn** [comment]
`graphql_transport_ws` is the handler for the `graphql-transport-ws` WebSocket subprotocol, which is the newer protocol. Unfortunately, it lives in a repository called `graphql-ws` which causes a lot of confusion, because that's also the name of the legacy WebSocket subprotocol.

**Comment by tjcutajar** [comment]
@DoctorJohn lol ok, thanks for clarifying.
