### ISSUE TITLE
Support for Apollo Tracing

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#40]
This should allow tracing performance problems in APIs made with Strawberry:

https://github.com/apollographql/apollo-tracing

**Comment by jaydenwindle** [comment]
There's been some discussion about this in the Graphene project (see https://github.com/graphql-python/graphene/issues/476), and it looks like fully supporting tracing will require changes to `graphql-core-next` in order to properly measure `parsing` and `validation` times, since middleware at the moment are limited to wrapping resolvers.

However, we should be able to measure resolver-level tracing data just fine using normal middleware.
