### ISSUE TITLE
Add AUTHORS file

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#53]
I think it would be nice to acknowledge all the contributors and add them to the AUTHORS file, as Django does. Maybe we can automate this with the deploy script, we could also mention people in the release notes, that would be really nice :D

https://github.com/django/django/blob/master/AUTHORS

**Comment by adamchainz** [comment]
FYI I removed authors files from my projects recently because after further contributions, they were out of sync. I'm not even sure the Django one is a good idea at this point, there are 1700 GitHub contributors and just 900 in the authors file. Although there may be duplicate GitHub accounts, and simple contributions like a few typo fixes, a lot of contributors have probably missed the file and gone uncredited tehrre.

**Comment by patrick91** [comment]
Uh, that's a good point :) 

I'll close this for now, maybe we can add a page on the website in the future (and use GitHub's API to fetch the contributors :) )
