### ISSUE TITLE
Allow to use init=False on fields

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#539]
Pretty much like dataclasses we should allow to skip fields from being included in the __init__ method, like this:

```python
@strawberry.type
class IceCream:
    num_scoops: int
    sequence_scoops: List['Flavour']
    example: str = dataclasses.field(init=False)
```

We should be able to do this:

```python
@strawberry.type
class IceCream:
    num_scoops: int
    sequence_scoops: List['Flavour']
    example: str = strawberry.field(init=False)
```

Edit:

We should also support `default` and `default_factory` on `strawberry.field`

**Comment by jkimbo** [comment]
@patrick91 when would you want to do this?

**Comment by patrick91** [comment]
@jkimbo I don't really have a usecase for it, it came through a conversation with @srbiotik :)

I guess it might be useful in combination with `strawberry.Private` 🤔

**Comment by jordangarside** [comment]
Say I have a model like:
```
@strawberry.type
class MyNode:
  a: str
  b: str
  c: str
```

And a resolver like this:
```
async def my_node_resolver(root, info) -> MyNode:
  return MyNode(a="", b="")
```

And I try to query:
```
query {
  myNode {
    a
    b
  }
}
```

This _should_ work fine, but you'll get an error saying that you didn't init c:
`"__init__() missing 1 required positional arguments: 'c'"`

`c` is not `Optional`, it's just not implemented yet.
Currently, if I were to do `MyNode(a="", b="", c="")` or if I added a field resolver to `c` then this query would work fine.

There are a couple issues with this:
- Since I didn't query for `c` the fact that it couldn't resolve shouldn't affect any queries not involving that field.
- Even if `c` _had a field resolver_ we don't actually want to call the field resolver here just to construct the class since it may be expensive and we didn't query for it.

Imo the **default** behavior should be:
- When you construct a class you shouldn't get a runtime error if all the fields are not passed in (even if there is no field resolver for those missing fields). It's reasonable for this to be type error.
- Field resolvers unrelated to the query should not be called.

^ these 2 are basically related to each other. I'm just not sure if there is a simple way to solve this without modifying the way `@strawberry.type` a bit.

**Comment by jordangarside** [comment]
I actually don't think `dataclasses.field(init=False)` really solves this problem since once you add that you can no longer pass `c` in when constructing the class -- and it also doesn't solve the unnecessary calling of fields unrelated to the query.

**Comment by patrick91** [comment]
> Field resolvers unrelated to the query should not be called.
This is already what's happening 😊

> Even if c had a field resolver we don't actually want to call the field resolver here just to construct the class since it may be expensive and we didn't query for it.
We don't call field resolver unless requested :)

> When you construct a class you shouldn't get a runtime error if all the fields are not passed in (even if there is no field resolver for those missing fields). It's reasonable for this to be type error.

I'm a bit wary of this, it does make sense, but I feel like it break the premise of using dataclasses and also it would break usage of objects in pure python 🤔 

What do you think @jkimbo @BryceBeagle?

> I actually don't think dataclasses.field(init=False) really solves this problem since once you add that you can no longer pass c in when constructing the class -- and it also doesn't solve the unnecessary calling of fields unrelated to the query.

would something like:

```python
@strawberry.type
class MyType:
   a: str
   b: str
   c: str = strawberry.field(implemented=False)
```

`implemented=False`[1] would basically keep c into `__init__` but it would it give a python-only default of None so when querying the field you'd get a GraphQL type error?

@jordangarside do you have another use case? I'm not 100% sure what you mean with this:

> c is not Optional, it's just not implemented yet.

If c is not implemented yet, do you want it to just show in the schema and fail when queries?
What about when you implement it? Would you like it to fail when using the class wrong?

[1] I just woke up and I couldn't think of a better name :)

**Comment by jkimbo** [comment]
I can't really see the use case for defining a field on a type but not implementing it. If you don't want to implement the field then you can assign a default value to it which should avoid the type error:

```python
@strawberry.type
class MyType:
   a: str
   b: str
   c: str = ""

MyType(a="", b="") # returns MyType(a="", b="", c="")
```

Am I missing something @jordangarside ?

---

> When you construct a class you shouldn't get a runtime error if all the fields are not passed in (even if there is no field resolver for those missing fields). It's reasonable for this to be type error.

I think it **is** reasonable for this to be a type error because you are using the type as a data container and if you miss a field that is required when instantiating that data container it should error (and mypy should complain). If you were just using plain dataclasses this behaviour would be expected. 

In the case where it might be too computationally intensive to provide all the values for a field that might not be queried by the client the field should define a resolver which can then fetch the value on demand. For example:

```python
@strawberry.type
class MyType:
    a: str
    b: str

    @strawberry.field
	def c(self):
		# Get the value of c here
		# This function will only be called if the client requests the `c` field
```

---

@patrick91 regarding adding and `init=False` field to `strawberry.field`: I don't think it's a good idea. It seems to me that the only reason for its use is so that you can define the field in a `__post_init__` method. That might have some benefit but IMO it's not worth the added API complexity. Open to changing my mind on this if a compelling use case comes up for it. Strong opinions, weakly held etc. 🙂

**Comment by jordangarside** [comment]
> > Field resolvers unrelated to the query should not be called.
> 
> This is already what's happening 😊
> 
> > Even if c had a field resolver we don't actually want to call the field resolver here just to construct the class since it may be expensive and we didn't query for it.
> 
> We don't call field resolver unless requested :)

Ohh gotcha, that's my bad. I assumed this was the case because this was working for queries that don't fetch the title:

```py
@strawberry.type
class Book:
    id: str

    @strawberry.field(name="title")
    async def resolve_title(self, info) -> str:
        return None


async def get_books():
    return [
        Book(id="1"),
        Book(id="2"),
    ]


@strawberry.type
class Query:
    books: typing.List[Book] = strawberry.field(resolver=get_books)
```
I was thinking this was calling the field resolver and that's why it was fulfilling the query. But, I just realized that the reason this works is because `title` is not an explicit field anymore. i.e. I can no longer do:
```py
Book(id="1", title="some title")
```
which I guess is expected, but that's not really great because now I can no longer pass in title from the root or from a parent node.

---

So I don't mind doing something like this in `get_books`:
```py
@strawberry.type
class Book:
    id: str
    title: str

async def get_books():
    return [
        Book(id="1", title=None), # type: ignore
        Book(id="2", title=None), # type: ignore
    ]
```
This basically behaves how I would expect it to. I think the one issue for me right now is that I actually don't get type hints that `title` is missing _and_ I don't get type hints if `title` is the wrong type.

![image](https://user-images.githubusercontent.com/6321824/97558648-a262b280-1999-11eb-942b-40c92781ed16.png)

Maybe my editor is just not setup correctly?

**Comment by patrick91** [comment]
> which I guess is expected, but that's not really great because now I can no longer pass in title from the root or from a parent node. 

What's the usecase for this? The resolver would always get called when executing the GraphQL query


Regarding the errors, we have a mypy plugin, it is described here: https://github.com/strawberry-graphql/strawberry#type-checking

I only want to mention that it's still beta/alpha, so it might crash in some instances, but I'm happy yo try to fix any issue with mypy 😊

**Comment by jordangarside** [comment]
> What's the usecase for this? The resolver would always get called when executing the GraphQL query

You can set your resolver up to default to the value passed in on `self`/`root`. That way if you already have the value from the parent context you can just pass it in. You might want to do this if the field is expensive to calculate.

> I think it is reasonable for this to be a type error because you are using the type as a data container and if you miss a field that is required when instantiating that data container it should error (and mypy should complain). If you were just using plain dataclasses this behaviour would be expected.

Ohh sorry, I wasn't clear here. I meant rather I would expect this to be a static type error rather than runtime. The issue with it being a runtime type error is that now you could potentially break in ways that don't actually affect your ability to resolve the query.

Say I had something like:
```py
@strawberry.type
class BookRoot:
    id: str
    title: str

async def get_books(root, info):
    if something == True: # maybe looking at some query information
        partial_data = info.data_sources.partial_loader.load(info.request.args.id)
        # ohh no, we didn't include title and now this will break at runtime even though it might not affect the query
        return [
            Book(id=partial_data.id)
        ]
    else:
        full_data = info.data_sources.full_loader.load(info.request.args.id)
        return [
            Book(id=full_data.id, title=full_data.title)
        ]
```
If we have a field resolver for title, then this will always work fine which is good.
But, in the event that we don't we're potentially failing at runtime unnecessarily. That can be fine, I just don't see why it's necessary to fail at runtime here. From my experience with other libraries you wouldn't fail here as there is no real reason to (other than the fact dataclasses are the underlying implementation).

The particular scenario I ran into this was because I hadn't implemented a field yet and wasn't querying for it, but I could have more complex behavior in my root resolver and I would prefer if the library didn't unnecessarily throw errors at runtime.

It's a bit hard to describe this, but hope that makes sense. 👍

**Comment by jordangarside** [comment]
> Regarding the missing type hints errors, we have a mypy plugin, it is described here: https://github.com/strawberry-graphql/strawberry#type-checking

Yeah I added the plugin, just not seeing any type errors around instantiating a class with missing/incorrect fields.

I'll try to take a look at this more a later.

**Comment by jordangarside** [comment]
I'll try to lay this out a bit more concisely later as well.

**Comment by jkimbo** [comment]
@jordangarside I think I understand now, thanks for explaining. IMO raising a runtime error when loading a type with partial data is the right behaviour because the server doesn't control the fields the client selects and so I would rather it broke earlier (ideally at type checking time) than later. If the data for a field could be missing then the field should either be optional or have a default value.

For dealing with partial data @jordangarside one option is to use the `Private` field (https://github.com/strawberry-graphql/strawberry/pull/479). For example:

```python
@strawberry.type
class Book:
    id: str
    data: strawberry.Private[Any]

	@strawberry.field
	def title(self) -> str:
		return self.data.get("title", "Untitled")

async def get_books(root, info):
    if something == True: # maybe looking at some query information
        partial_data = info.data_sources.partial_loader.load(info.request.args.id)
        return [
            Book(id=partial_data.id, data=partial_data)
        ]
    else:
        full_data = info.data_sources.full_loader.load(info.request.args.id)
        return [
            Book(id=full_data.id, data=full_data)
        ]
```

**Comment by patrick91** [comment]
@jordangarside thanks for explaining! maybe we could allow types to be partially initialised, like this:

```python
@strawberry.type(partial=True)
class BookRoot:
    id: str
    title: str
```

or even more explicit:

```python
@strawberry.type
class BookRoot:
    id: str
    title: str

BookRoot.partial(id="123")
```

I throwing out ideas here, as I agree with @jkimbo here:

> so I would rather it broke earlier (ideally at type checking time) than later.

but I think we can allow for partial initalization since there's usecases for it, I just would like to make it as explicity as possible, what do you think?

**Comment by srbiotik** [comment]
> but I think we can allow for partial initalization since there's usecases for it, I just would like to make it as explicity as possible, what do you think?

The second one feels better. Saves the pain of defining init for each field also.

**Comment by m-yakovenko** [comment]
Hi there. I am not sure, that is an issue, that's why I hope to find out this here. I have a similar issue about skipping a field, but on the schema level. 

I haven't found mentions about this feature in the doc. Here is the thing, I have a Query class with its internal dependencies which are declared as class variables. However, they are not the part of the schema. Here is the snippet:
```
@strawberry.type
class Query:
   engine: DbEngine # not the part of the schema

    def __init__(self, engine: DbEngine):
        self.engine = engine

    @strawberry.field
    async def rubric(self) -> List[Rubric]:
        return await self.engine.find(Rubric)

```
Partially, I managed this by removing the class variable, but I looks not so obvious I guess. So, it would be great to have a way to mark explicitly the field `engine` to be skipped by `GraphQLSchema` generator, e.g:
```
class Query:
   engine: DbEngine = Field(skip=True) # not the part of the schema

    def __init__(self, engine: DbEngine):
        self.engine = engine

    @strawberry.field
    async def rubric(self) -> List[Rubric]:
        return await self.engine.find(Rubric)

```

**Comment by patrick91** [comment]
@m-yakovenko you can use strawberry.Private for that :)

```python

class Query:
   engine: strawberry.Private[DbEngine]

    @strawberry.field
    async def rubric(self) -> List[Rubric]:
        return await self.engine.find(Rubric)

```

**Comment by jimmybutton** [comment]
This repository contains some great ideas on how to use strawberry extensions to provide a database session to your queries: https://github.com/strawberry-graphql/examples/blob/main/fastapi-sqlalchemy/api/schema.py

**Comment by patrick91** [comment]
@jimmybutton was this the right issue you wanted to comment on? 😊

I'll close this issue for now, we added `init` to `strawberry.field` because it was needed for type checkers (it's used in dataclass_transform). We can open another issue for partial types in future if needed 😊

**Comment by jimmybutton** [comment]
Yeah true, it's probably not related to this issue. But this thread came up in the search results when I was looking for a solution to provide a database session to the resolvers. The example repo has some great patterns for this problem, so I wanted to leave a trace for others people coming here with a similar issue. 😊

**Comment by patrick91** [comment]
@jimmybutton gotcha! thanks for that 😊
