### ISSUE TITLE
Question: when must you declare types on Schema?

### ISSUE THREAD

**Issue by ossareh** [strawberry-graphql/strawberry#610]
Related to #607 (where things like procs are created, etc):

```
@strawberry.type
class LogBlob:
    stdout: Optional[str]
    stderr: Optional[str]
    returncode: Optional[int]


@strawberry.type
class Subscription:
    @strawberry.subscription
    async def tail_command(self, pid: int) -> AsyncIterator[LogBlob]:
        async for line in tail(pid=pid):
            proc = get(pid=pid)
            yield LogBlob(stdout=line[0], stderr=line[1], returncode=proc.returncode)
```

will generate this error when I try to start strawberry:

```
TypeError: Subscription fields cannot be resolved. Unable to get GraphQL type for typing.AsyncIterator[guvnor.schema.choreography.LogBlob]
```

That's fixable with `schema = Schema(types=[LogBlob])`. It's also fixable by changing the `AsyncIterator[LogBlob]` -> `AsyncGenerator[LogBlob, None]`.

If someone can help me understand why this happens I'm down to update the docs accordingly so that future me's don't stumble into this!

**Comment by BryceBeagle** [comment]
I'm guessing this is because the logic here is not triggered: 
https://github.com/strawberry-graphql/strawberry/blob/ddb2cb77ae8df1ca7e7fc044531a2c6d1c237a92/strawberry/types/type_resolver.py#L89-L96

Note this this is function (`resolve_type`) is probably going to change drastically or even  be removed when [feature/strawberry_type](https://github.com/strawberry-graphql/strawberry/tree/feature/strawberry_type) is merged

**Comment by patrick91** [comment]
This might have been resolved, I've just tested your code @ossareh and it didn't fail for me. I'll close the issue, happy to reopen it if this still happens for you :)
