### ISSUE TITLE
Allow throwing a custom exception or expose a "code" when a permission check fails

### ISSUE THREAD

**Issue by marcoacierno** [strawberry-graphql/strawberry#704]
Right now any check that fails in the permission_fields of a field raise a `PermissionError`

https://github.com/strawberry-graphql/strawberry/blob/ceb555f8cfe6526bc9e7982d36e21bbe2b7b4a35/strawberry/resolvers.py#L91

in some cases it might useful to change the behaviour of the GraphQLView based on what permission error happened

E.g in our case when the token is not valid we have a `ValidTokenPermission` and we need to change the behaviour of the view to return a 401. Right now we check the exception message but it's ideal

The solution might be to :

1. Allow Custom exceptions to be raised
2. Change the PermissionClasses to also have a `code`, and raise a custom `StrawberryPermissionDenied` exception so you can access `.code` in the view

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/704">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/704/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/704/pledge.svg">
</picture>
</a>

**Comment by jthorniley** [comment]
I like this idea. Also, strawberry currently uses PermissionError from the standard library, which is a subclass of OSError and seems to be really intended for:

> when a system function returns a system-related error, including I/O failures such as “file not found” or “disk full” (not for illegal argument types or other incidental errors).

https://docs.python.org/3/library/exceptions.html?highlight=permissionerror#OSError

With `PermissionError` encapsulating certain error codes like EACCES.

Since this is generally unlikely to be the reason for a permission error in strawberry it doesn't seem like the right exception, I'd vote for a custom strawberry exception type with a way for the content to be customised.

**Comment by DoctorJohn** [comment]
Both throwing a custom exception and adding a "code" has been possible for a few months now. Here's the relevant section in the docs: https://strawberry.rocks/docs/guides/permissions#advanced-permissions

Feel free to open a new issue if either of your feel like your use case is not fully addressed by this :)
